const getRandom = require('./index')

console.log(getRandom('fotfSpell'))
console.log(getRandom('fotfSpell'))
console.log(getRandom('fotfSpell'))
console.log(getRandom('fotfSpell'))
console.log(getRandom('fotfSpell'))
console.log(getRandom('fotfSpell'))
console.log(getRandom('fotfSpell'))
console.log(getRandom('fotfSpell'))
console.log(getRandom('fotfSpell'))
console.log(getRandom('fotfSpell'))
console.log(getRandom('fotfSpell'))
console.log(getRandom('fotfSpell'))
console.log(getRandom('fotfSpell'))
