const sample = require('../utils/sample')

module.exports = () => {
  return sample([
    'Salamander',
    'Hellbender',
    'Lizard',
    'Iguana',
    'Komodo Dragon',
    'Monitor',
    'Chameleon',
    'Toad',
    'Turtle',
    'Tortoise',
    'Triceratops',
    'Stegadon',
    'Ankylosaurus',
    'T-Rex',
    'Allosaurus',
    'Dimetrodon',
    'Snake',
    'Cobra',
    'Viper',
    'Python',
    'Crocodile',
    'Alligator',
    'Gharial',
    'Pterodactly',
    'Pterosaur',
    'Archaeopteryx',
    'Frog',
    'Bull Frog',
    'Poison Arrow',
    'Raptor',
    'Deinonychus',
    'Velociraptor',
    'Oviraptor',
    'Pachycephalosaurus',
    'Iguanadon',
    'Hadrosaur',
    'Newt',
    'Pliosaur',
    'Plesiosaur',
    'Ichthyosaur',
    'Bat',
    'Terror Bird',
    'Bear',
    'Polar Bear',
    'Panda',
    'Elephant',
    'Rhino',
    'Hippo',
    'Woolly Mammoth',
    'Seagull',
    'Albatross',
    'Rat',
    'Mouse',
    'Mole',
    'Rabbit',
    'Primate',
    'Gorilla',
    'Chimp',
    'Orangutan',
    'Bonobo',
    'Lemur',
    'Hawk',
    'Eagle',
    'Condor',
    'Boar',
    'Goat',
    'Stag',
    'Moose',
    'Vulture',
    'Raven',
    'Crow',
    'Canine',
    'Dog',
    'Wolf',
    'Coyote',
    'Fox',
    'Jackal',
    'Feline',
    'Lion',
    'Tiger',
    'Puma',
    'Hyena',
    'Ostrich',
    'Emu',
    'Cassowary',
    'Weasel',
    'Badger',
    'Wolverine',
    'Ferret',
    'Ungulate',
    'Zebra',
    'Antelope',
    'Gnu',
    'Horse',
    'Centipede',
    'Millipede',
    'Eel',
    'Fish',
    'Pike',
    'Trout',
    'Pirahna',
    'Slug',
    'Worm',
    'Snail',
    'Angler Fish',
    'Squid',
    'Octopus',
    'Locust',
    'Mantis',
    'Ant',
    'Crab',
    'Lobster',
    'Manta Ray',
    'Bee',
    'Hornet',
    'Wasp',
    'Shark',
    'Beetle',
    'Roach',
    'Scarab',
    'Spider',
    'Scorpion',
    'Fly',
    'Mosquito',
    'Jellyfish',
    'Man o\' War'
  ])
}
