const sample = require('./utils/sample')
module.exports = () => {
  return sample([
    'abaya',
    'agal',
    'ajkača',
    'alice band',
    'american fiber helmet',
    'anthony eden hat',
    'aqal',
    'arab headdress',
    'archer\'s bonnet',
    'asian conical hat',
    'aso oke hat',
    'aviator\'s cap',
    'balaclava',
    'balibuntal',
    'balmoral bonnet',
    'bandana',
    'bandeau hat',
    'barretina',
    'basher',
    'bashlyk',
    'battoulah',
    'bearskin hat',
    'beaver hat',
    'beefeaters\' hat',
    'beehive',
    'beret',
    'bergère hat',
    'bersagliere',
    'bhatgaunle topi',
    'bicorne',
    'billycock',
    'bird cage',
    'biretta',
    'black cap',
    'blangkon',
    'bloomer',
    'blue bonnet',
    'boater',
    'bongrace',
    'bonnet head',
    'boonie hat',
    'boss of the plains',
    'boudoir cap',
    'boushiya',
    'bowler',
    'boxer',
    'breton',
    'brodrick cap',
    'buknuk',
    'bun hat',
    'burga',
    'busby',
    'bycocket',
    'cabbage-tree hat',
    'cabriolet',
    'camauro',
    'campaign hat',
    'canterbury cap',
    'cap and bells',
    'cap comforter',
    'cap of maintenance',
    'cape ann,',
    'capeline',
    'capirote',
    'capotain',
    'capote',
    'cappello romano',
    'cartwheel hat',
    'casquette or cycling cap',
    'castor',
    'caubeen',
    'cavalier hat',
    'chador',
    'chapeau-bras',
    'chaperon',
    'cheich',
    'chip bonnet',
    'chip hat',
    'chullo',
    'chupalla',
    'cloche',
    'clop',
    'cockle hat',
    'cocktail hat',
    'coif',
    'coke hat',
    'colback',
    'combination cap',
    'cony',
    'coolie hat',
    'coonskin hat',
    'copintank',
    'cordies',
    'cork hat',
    'coronet',
    'cossack hat',
    'cowboy hat',
    'cricket cap',
    'crispine',
    'crown',
    'cucupha',
    'custodian helmet',
    'deerstalker',
    'demicastor hat',
    'derby',
    'diadem',
    'digger hat',
    'directoire',
    'diving mask',
    'do-rag',
    'dogon hat',
    'doll hat',
    'dolly varden',
    'dunce cap',
    'dupatta',
    'energy dome',
    'envelope busby',
    'fan-tail hat',
    'fascinator',
    'feather bonnet',
    'feathered headdress',
    'fedora',
    'fez',
    'firefighter\'s helmet',
    'flat cap',
    'flat',
    'flemish hood',
    'flying helmet',
    'forage cap',
    'four winds hat',
    'french hood',
    'fulani hat',
    'full-face diving mask',
    'gable hood',
    'gahfiah',
    'gainsborough hat',
    'galero',
    'galician',
    'garbo hat',
    'gargush',
    'garibaldi',
    'garrison cap',
    'gas mask',
    'gasa',
    'għonnella',
    'gipsy hat',
    'glengarry bonnet',
    'golden hat',
    'gossamer hat',
    'grebe hat',
    'green eyeshade',
    'gypsy bonnet',
    'haida hat',
    'half hat',
    'halo hat',
    'hardee hat',
    'hat terrai gurkha',
    'havalim',
    'headband',
    'headscarf',
    'helmet',
    'hennin',
    'hijab',
    'holy crown of hungary',
    'homburg',
    'hood',
    'hunting hat',
    'icelandic tail-cap',
    'igal',
    'imperial crown of india',
    'imperial state crown',
    'irish walking hat',
    'jaapi',
    'jeep cap',
    'jerry',
    'jockey\'s cap',
    'juliet cap',
    'kalimavkion',
    'kalpak',
    'kartus',
    'kashket',
    'kausia',
    'keffiyeh',
    'kepi',
    'kevenhuller',
    'khimar',
    'kippah',
    'kiss-me-quick hat',
    'klobuk',
    'kofia',
    'kokoshnik',
    'kolpik',
    'koukoulion',
    'kufi',
    'latex mask',
    'leghorn bonnet',
    'leghorn hat',
    'leopard cap',
    'litham',
    'lungee',
    'mandarin hat',
    'mandily',
    'manilla hat',
    'mantilla',
    'marquis hat',
    'mary queen of scots',
    'matinée hat',
    'medieval hood',
    'merry widow hat',
    'migba\'at',
    'milfeh',
    'ming official headwear',
    'mirliton',
    'mitre',
    'mitznefet',
    'moab',
    'mob-cap',
    'mokorotlo',
    'monmouth cap',
    'montenegrin cap',
    'montera',
    'mourning bonnet',
    'mourning hat',
    'mourning hood',
    'mousquetaire',
    'mukut',
    'müller hat',
    'mushroom',
    'nemes',
    'night cap',
    'niqab',
    'nón lá',
    'nón quai thao',
    'nurse\'s cap',
    'ochipok',
    'ogal',
    'orthodontic facemask',
    'pagri',
    'pakol',
    'pamela hat',
    'pan zva',
    'panama hat',
    'papakha',
    'papal tiara',
    'party hat',
    'patrol cap',
    'pava',
    'peaked cap',
    'peci',
    'perak',
    'petasos',
    'pheta',
    'phrygian cap',
    'phylacteries',
    'pickelhaube',
    'pileus',
    'pill box hat',
    'pillbox cap',
    'pinner',
    'pith helmet',
    'pointy hat',
    'poke bonnet',
    'pork pie',
    'printer\'s hat',
    'propeller hat',
    'pussyhat',
    'qeleshe',
    'qing official headwear',
    'quadricorn',
    'rasam pagri',
    'riding hood',
    'sailor cap',
    'salakot',
    'santa\'s hat',
    'sarpech',
    'scrum cap',
    'shako',
    'sheitel',
    'shmagh',
    'shovel hat',
    'shower cap',
    'shripech',
    'shtreimel',
    'sikh turban',
    'skimmer',
    'skufia',
    'slouch hat',
    'smagh',
    'smoking cap',
    'snood',
    'sombrero',
    'song official headwear',
    'songkok',
    'sou\'wester',
    'space helmet',
    'spodik',
    'square academic cap',
    'st edward\'s crown',
    'stocking cap',
    'stormy kromer cap',
    'stuart hood',
    'sudra',
    'sugar loaf',
    'swimming cap',
    'tagelmust',
    'tam o\'shanter',
    'tang official headwear',
    'tantour',
    'taqiya',
    'tarleton helmet',
    'ti\'i langga',
    'tiara',
    'tin foil',
    'top hat',
    'topor',
    'toque',
    'tricorne',
    'trilby',
    'tudong',
    'turban',
    'umbrella hat',
    'ushanka',
    'veil',
    'veiled hat',
    'visor',
    'war bonnet',
    'watermelon helmet',
    'wedding veil',
    'welsh hat',
    'whoopee cap',
    'wimple',
    'wreath',
    'yarmulke',
    'zucchetto',
    'zulu crown'
  ])
}
