import sample from '../utils/sample'

export default () => sample([
  'actor',
  'actress',
  'puppeteer',
  'marionetteer',
  'actuary',
  'administrative worker',
  'advertising manager',
  'aerial rigger',
  'adviser',
  'mechanic',
  'agronomist',
  'air traffic controller',
  'air traffic safety technician',
  'aircraft instrument technician',
  'aircraft mechanic',
  'airline clerk',
  'airline ticket agent',
  'munitions worker',
  'animal technician',
  'animator',
  'anthropologist',
  'applications manager',
  'apprentice training officer',
  'trainer',
  'instructor',
  'archeologist',
  'architect',
  'architectural conservation officer',
  'art critic and historian',
  'art glazier and window-pane maker',
  'glazier',
  'art metalworker',
  'locksmith',
  'art photographer',
  'art restorer',
  'articled clerk',
  'legal assistant',
  'artificial flower maker',
  'artistic promotions manager',
  'assessor',
  'insurance assessor',
  'assistant housekeeper',
  'domestic help',
  'assistant printing worker',
  'astrologer',
  'astronomer',
  'athlete',
  'sportsman',
  'auctioneer',
  'audio graphic designer',
  'auditor',
  'electrician',
  'auxiliary shop assistant',
  'shop worker',
  'shelf filler',
  'auxiliary worker',
  'geological survey worker',
  'woodcutter',
  'baker',
  'bank clerk',
  'banking expert',
  'barber',
  'hairdresser',
  'barman',
  'barmaid',
  'bartender',
  'basket-maker',
  'basket-weaver',
  'beautician',
  'beauty therapist',
  'beekeeper',
  'bibliographer',
  'biochemist',
  'biologist',
  'biotechnologist',
  'biscuit maker',
  'blacksmith',
  'farrier',
  'blasters foreman',
  'explosives expert',
  'blast-furnaceman',
  'blasting works engineer',
  'boatman',
  'bargee',
  'boiler operator',
  'boiler attendant',
  'boilermaker',
  'bookbinder',
  'bookkeeper',
  'bookmaker',
  'botanist',
  'brewer',
  'maltster',
  'bricklayer',
  'broadcaster',
  'announcer',
  'radio broadcaster',
  'telecaster',
  'brush-maker',
  'builder',
  'laborer',
  'building and road machinery mechanic',
  'building electrician',
  'building fitter',
  'building locksmith',
  'building inspector',
  'building machine operator',
  'building materials production operative',
  'building tinsmith',
  'architectural technician',
  'technologist',
  'butcher and sausage-maker',
  'butler',
  'button maker',
  'taxi dispatcher',
  'cabinet maker',
  'cable car driver',
  'cable maker',
  'camera mechanic',
  'camera operator',
  'canning worker',
  'cannery operator',
  'capital markets clerk',
  'officer',
  'captain of an aircraft',
  'car mechanic',
  'car service worker',
  'service station worker',
  'care assistant',
  'home care assistant',
  'home care organiser',
  'career diplomat',
  'diplomat',
  'career guidance counsellor',
  'caretaker',
  'carpenter',
  'cartographer',
  'cellulose operator',
  'ceramic model maker',
  'ceramic painter',
  'ceramicist',
  'potter',
  'charter agent',
  'ship broker',
  'cheese maker',
  'chemical industries operative',
  'chemical operator',
  'chemical industry production manager',
  'chemical laboratory technician',
  'laboratory assistant',
  'chemical researcher',
  'chemical technologist',
  'senior guard',
  'children\'s nurse',
  'child\'s nurse',
  'chimney sweep',
  'choir master',
  'choir mistress',
  'choreographer',
  'circus artiste',
  'circus performer',
  'cleaner',
  'cloakroom attendant',
  'coffee roaster',
  'coffeehouse keeper',
  'café owner',
  'commentator',
  'reporter',
  'journalist',
  'commercial lawyer',
  'company lawyer',
  'composer',
  'computer engineer',
  'information technology engineer',
  'computer equipment operator',
  'information technology operator',
  'computer network manager',
  'computer programmer',
  'systems programmer',
  'applications programmer',
  'concrete worker',
  'concreter',
  'conductor',
  'confectioner',
  'conservator',
  'construction carpenter',
  'joiner',
  'construction site manager',
  'site manager',
  'cook',
  'corrosion control fitter',
  'court executive officer',
  'bailiff',
  'craft ceramicist',
  'craft gilder',
  'craft glass etcher',
  'craft glassmaker',
  'craft metal founder and chaser',
  'craft metalworker and brazier',
  'craft mosaic maker',
  'craft plasterer',
  'craft stonemason',
  'craft upholsterer',
  'crane driver',
  'crane operator',
  'crate maker',
  'cooper',
  'criminal investigator',
  'crop treatment operative',
  'croupier',
  'customs officer',
  'customs inspector',
  'cutler',
  'dairy worker',
  'dairy operator',
  'dance teacher',
  'dance trainer',
  'dancer',
  'data transfer appliance technician',
  'debt collector',
  'decorator',
  'paperhanger',
  'dental surgery assistant',
  'dental nurse',
  'dental technician',
  'dentist',
  'dental surgeon',
  'developing and printing technician',
  'photographic laboratory assistant',
  'dietician',
  'digger',
  'director',
  'disc jockey',
  'dish washer',
  'dispatch clerk',
  'dispatcher',
  'diver',
  'dog trainer',
  'doorkeeper',
  'porter',
  'draughtsperson',
  'draughtsman',
  'draughtswoman',
  'dresser',
  'driller',
  'drilling rig operator',
  'driver',
  'driver\'s mate',
  'driver\'s assistant)',
  'driving instructor',
  'dust control technician',
  'ecologist',
  'environmentalist',
  'economist',
  'company accountant',
  'editor',
  'specialist editor',
  'educational methods specialist',
  'electrical and power systems design engineer',
  'electrical equipment design engineer',
  'electrical equipment inspector',
  'electrical fitter',
  'electrical mechanic',
  'electrician',
  'electroceramic production operative',
  'electronic equipment mechanic',
  'electronic engineering technician',
  'electroplating operator',
  'galvaniser',
  'employment agent',
  'employment officer',
  'enamel worker',
  'engineering fitter',
  'machine fitter',
  'engineering maintenance technician',
  'plant technologist',
  'entertainment officer',
  'environmental protection inspector',
  'environmental inspector',
  'ergonomist',
  'ethnographer',
  'exhibitions production manager',
  'faith healer',
  'farm worker',
  'farm labourer',
  'farmer',
  'fashion designer',
  'feed production operator',
  'film critic',
  'film designer',
  'film set designer',
  'film or videotape editor',
  'film projectionist',
  'financial analyst',
  'financial officer',
  'fine artist',
  'fire officer',
  'fire officer',
  'firefighter',
  'fire prevention officer',
  'fire inspector',
  'fish farmer',
  'fish warden',
  'water keeper',
  'fisherman',
  'fitter',
  'flight attendant',
  'steward',
  'stewardess',
  'flight engineer',
  'floor fitter',
  'floor layer',
  'grower',
  'flying instructor',
  'food industry production manager',
  'food industry technologist',
  'foreign exchange clerk',
  'teller',
  'foreign exchange office clerk',
  'forester',
  'forestry manager',
  'forest manager',
  'forestry machine operator',
  'forestry worker',
  'fortune teller',
  'foster parent',
  'foundry worker',
  'foundry process operator',
  'coremaker',
  'patternmaker',
  'fruit farmer',
  'fruit grower',
  'funeral service assistant',
  'funeral service worker',
  'fur coat seamstress',
  'fur coat sewer',
  'furnace operator',
  'furrier',
  'gardener',
  'market gardener',
  'gas industry inspector',
  'general labourer',
  'geneticist',
  'geographer',
  'geological surveying equipment mechanic',
  'geologist',
  'geophysicist',
  'glass decorator',
  'glass engraver',
  'glass jewellery maker',
  'glass making machine operator',
  'glass melter',
  'glass painter',
  'glass production worker',
  'glasscutter',
  'glass grinder',
  'glassworker',
  'glazier',
  'goldsmith',
  'government licensing official',
  'graphic designer',
  'gravedigger',
  'guide',
  'gunsmith',
  'hand embroiderer',
  'hand lacemaker',
  'harbour guard',
  'hardener',
  'harpooner',
  'hatter',
  'hat maker',
  'heating and ventilating fitter',
  'heating engineer',
  'herbalist',
  'steeplejack',
  'historian',
  'historical monuments administrator',
  'custodian',
  'warden of a historic building',
  'horse breeder',
  'horse breeder and trainer',
  'host',
  'hostess',
  'hotel porter',
  'hotel receptionist',
  'receptionist',
  'hydrologist',
  'ice-cream maker',
  'image consultant',
  'industrial designer',
  'information assistant',
  'insulation worker',
  'insulator',
  'insurance clerk',
  'insurance sales person',
  'collector',
  'insurance underwriter',
  'interior designer',
  'interpreter and translator',
  'investment clerk',
  'invoice clerk',
  'jeweller',
  'goldsmith',
  'silversmith',
  'jewellery designer',
  'jewellery maker',
  'joiner and cabinetmaker',
  'joiner',
  'judge',
  'keeper of records',
  'archivist',
  'keeper of service animals',
  'knitter',
  'land surveyor',
  'landscape architect',
  'laundry worker',
  'dry-cleaner',
  'laundry worker',
  'dry cleaning worker',
  'lecturer',
  'librarian',
  'information scientist',
  'lifeguard',
  'swimming instructor',
  'lift attendant',
  'lift fitter',
  'lighting technician',
  'lightning conductor fitter',
  'lithographer',
  'livestock farmer',
  'lottery ticket street vendor',
  'machine shop worker',
  'machinery inspector',
  'make-up artist',
  'wigmaker',
  'management accountant',
  'management consultant',
  'manager',
  'marine engineer',
  'ship\'s engineer and machine operator',
  'marine hotel manager',
  'marketing manager',
  'masseur',
  'masseuse',
  'master of ceremonies',
  'materials handler',
  'mathematician',
  'medical laboratory assistant',
  'medical laboratory technician',
  'measurement and control technician',
  'mechanic',
  'service mechanic',
  'mechanical engineering designer',
  'mechanical engineering production manager',
  'mechanical engineering technologist',
  'mechatronic engineer',
  'metal engraver',
  'metal grinder',
  'metal refiner',
  'metal turner',
  'metal worker',
  'steelworker',
  'foundry worker',
  'metallurgist',
  'materials technician',
  'meteorologist',
  'metrologist',
  'microbiologist',
  'midwife',
  'miller',
  'milling-machine operator',
  'mine rescue service mechanic',
  'mine ventilation technician',
  'mine ventilation engineer',
  'miner',
  'mining air control technician',
  'mining finisher',
  'mining dresser',
  'mining machine operator',
  'mining mechanic',
  'mining fitter',
  'mining rescue worker',
  'minerals surveyor',
  'model',
  'fashion model',
  'supermodel',
  'modeller',
  'model maker',
  'mountain guide',
  'multimedia designer',
  'multimedia programmer',
  'web site designer',
  'municipal police officer',
  'policeman',
  'policewoman',
  'municipal services worker',
  'municipal street cleaner',
  'museum curator',
  'art gallery curator',
  'music director',
  'musical instrument mechanic',
  'musical instrument technician',
  'musician',
  'musicologist',
  'nanny',
  'nursery nurse',
  'naturalist',
  'nature guide',
  'reserve warden',
  'newspaper editor',
  'journalist',
  'nuclear power station operator',
  'nurse',
  'nursery school teacher',
  'nursery teacher',
  'nutritionist',
  'office junior',
  'on-line customer services operator',
  'operational analyst',
  'operational researcher',
  'operator',
  'optical component maker',
  'lens grinder',
  'optical instrument mechanic',
  'ore crusher',
  'orthopaedic shoemaker',
  'orthopaedic bootmaker',
  'orthotic / prosthetic technician',
  'orthotist',
  'prosthetist',
  'packer',
  'paediatrician',
  'palmists',
  'paper worker',
  'paramedic',
  'ambulance worker',
  'patent agent',
  'paver',
  'asphalt layer',
  'road worker',
  'pawnbroker',
  'pedicurist',
  'manicurist',
  'personnel officer',
  'pest control officer',
  'petroleum and petrochemical process operators',
  'pharmaceutical operator',
  'pharmaceutical laboratory technician',
  'pharmaceutical laboratory assistant',
  'pharmacist',
  'philosopher',
  'photographer',
  'press photographer',
  'physicist',
  'physiotherapist',
  'piano tuner',
  'pilot',
  'pipe fitter',
  'pizza maker',
  'plumber',
  'plywood maker',
  'police clerk',
  'police investigator',
  'detective',
  'police officer',
  'police inspector',
  'political scientist',
  'pollster',
  'post office counter clerk',
  'postal service worker',
  'postal transport worker',
  'postal worker',
  'postman',
  'postwoman',
  'postmaster',
  'postmistress',
  'poultry breeder',
  'poultry farmer',
  'poultry butcher',
  'poulterer',
  'powder metallurgist',
  'power engineering specialist',
  'power station supervisor',
  'power system worker',
  'power truck driver',
  'prefab construction worker',
  'press officer',
  'public relations officer',
  'pricing officer',
  'priest',
  'minister',
  'clergyman',
  'clergywoman',
  'primary school teacher',
  'printer',
  'printing machine mechanic',
  'printing technician',
  'prison guard',
  'prison officer',
  'private detective',
  'producer',
  'product designer',
  'industrial designer',
  'production manager',
  'production technologist',
  'professional soldier',
  'prompter',
  'property manager',
  'props master',
  'psychiatrist',
  'psychologist',
  'psychotherapist',
  'public administration officer',
  'public notary',
  'public relations manager',
  'publican',
  'landlord',
  'landlady',
  'publisher',
  'purchasing officer',
  'buyer',
  'merchandiser',
  'quality control technician',
  'quality inspector',
  'radio and tv technician',
  'radio and tv transmission engineering technician',
  'radio officer',
  'radio operator',
  'radiographer',
  'radiotherapist',
  'rail transport worker',
  'rail vehicle mechanic',
  'railway carriage and wagon inspector',
  'railway electrician',
  'rail transport electrician',
  'railway engine mechanic',
  'railway freight handler',
  'railway guard',
  'guard',
  'railway operative',
  'railway administrative worker',
  'railway ticket / booking office clerk',
  'railway track construction fitter',
  'railway yard worker',
  'real estate agent',
  'estate agent',
  'referee',
  'umpire',
  'refrigeration engineer',
  'refrigeration mechanic',
  'refuse collector',
  'registrar',
  'removal worker',
  'furniture removal worker',
  'reproduction technician',
  'photographer',
  'retoucher',
  'river basin keeper',
  'river manager',
  'road sign assistant',
  'road sign keeper',
  'road transport technician',
  'rolling-mill operator',
  'roofer',
  'roof tiler',
  'slater',
  'chambermaid',
  'rope maker',
  'rotating machine fitter',
  'rubber operator',
  'rubber processing machine operator',
  'tyrefitter',
  'safety and communication electrician',
  'safety engineer',
  'health and safety inspector',
  'sales assistant',
  'salesperson',
  'salesman',
  'sales manager',
  'sales representative',
  'commercial traveller',
  'scaffolder',
  'scene painter',
  'scene-shifter',
  'script editor',
  'script writer',
  'scriptwriter',
  'sculptor',
  'seaman',
  'secondary school teacher',
  'secretary',
  'personal assistant',
  'section supervisor',
  'security guard',
  'service mechanic',
  'repairer',
  'sewerage system cleaning operator',
  'sewerage cleaner',
  'sewing machinist',
  'shepherd',
  'goatherd',
  'shift engineer',
  'ship fitter',
  'shipwright',
  'ship\'s captain',
  'ship\'s officer',
  'shoemaker',
  'cobbler',
  'cashier',
  'shunter',
  'shunting team manager',
  'school caretaker',
  'school inspector',
  'silkworm breeder',
  'sericulturist',
  'singer',
  'smith',
  'social worker',
  'sociologist',
  'solicitor',
  'songwriter',
  'sound effects technician',
  'sound engineer',
  'spa resort attendant',
  'baths assistant',
  'special educational needs teacher',
  'special effects engineer',
  'specialist in animal husbandry',
  'livestock specialist',
  'spectacle frame maker',
  'speech therapist',
  'spinner',
  'stable hand',
  'groom',
  'stage costume maker',
  'stage designer',
  'theatre designer',
  'stage manager',
  'standards engineer',
  'state attorney',
  'public prosecutor',
  'station manager',
  'statistician',
  'stockbroker',
  'stonemason',
  'stonecutter',
  'storekeeper',
  'warehouse keeper',
  'stove fitter',
  'stuntman',
  'stuntwoman',
  'sugar maker',
  'surgical toolmaker',
  'surveyor\'s assistant',
  'helper',
  'sweet factory worker',
  'sweet maker',
  'systems designer',
  'systems analyst',
  'systems engineer',
  'tailor',
  'dressmaker',
  'tamer',
  'lion tamer',
  'tanner',
  'tannery worker',
  'tax specialist',
  'tax adviser',
  'consultant',
  'technical editor',
  'technologist',
  'telecommunications cable fitter',
  'telecommunications dispatcher',
  'telecommunications engineer',
  'telecommunications installation and repair technician',
  'telecommunications mechanic',
  'telecommunications technician',
  'telecommunications worker',
  'telephone operator',
  'switchboard operator',
  'teller',
  'textile printer',
  'textile refiner',
  'textile technologist',
  'textiles dyer',
  'doctor',
  'hygiene service assistant',
  'medical orderly',
  'optician',
  'optometrist',
  'ticket collector',
  'ticket inspector',
  'tinsmith',
  'tobacco technologist',
  'tool setter',
  'toolmaker',
  'town planner',
  'track engineer',
  'tracklayer',
  'tractor-driver',
  'trading standards officer',
  'weights and measures inspector',
  'traffic police officer',
  'train dispatcher',
  'train driver',
  'engine driver',
  'apprentice chef',
  'sports trainer',
  'coach',
  'trainman',
  'trainwoman',
  'tram driver',
  'transport supervisor',
  'transportation supervisor',
  'travel agency clerk',
  'travel courier',
  'tourist guide',
  'tunneller',
  'tunnel builder',
  'tutor',
  'governess',
  'home tutor',
  'typesetter',
  'upholsterer',
  'usher',
  'usherette',
  'valuer',
  'varnisher',
  'veterinary surgeon',
  'veterinary technician',
  'animal nurse',
  'veterinary assistant',
  'veterinarian',
  'viniculturist',
  'wine-grower)',
  'wages clerk',
  'waiter',
  'waitress',
  'wardrobe master',
  'wardrobe mistress',
  'warehouse clerk',
  'waste incineration plant worker',
  'water management controller',
  'water supply and distribution manager',
  'water supply and distribution equipment operator',
  'water treatment plant operator',
  'water meter reader',
  'watercourse manager',
  'river administrator',
  'watchmaker',
  'watchman',
  'watchwoman',
  'security guard',
  'weaver',
  'weigher',
  'weir and dam operator',
  'welding operator',
  'welder',
  'well digger',
  'whaler',
  'window cleaner',
  'window-dresser',
  'winery worker',
  'wine maker',
  'wire-drawer',
  'wood carver',
  'wood industry technologist',
  'woodcutting manager',
  'woodworking operator',
  'wood machinist',
  'worker',
  'foundry worker',
  'zookeeper',
  'king',
  'queen',
  'boss',
  'chief',
  'rajah',
  'khan',
  'duke',
  'baron',
  'earl',
  'knight',
  'prince',
  'princess',
  'marquise'
])
