export const ANIMAL = 'ANIMAL'

export const BODYPART = 'BODYPART'

export const CLASS = 'CLASS'

export const DESCRIPTOR = 'DESCRIPTOR'

export const JOB = 'JOB'

export const NOUN = 'NOUN'

export const OATH = 'OATH'

export const WEAPON = 'WEAPON'

export const HAT = 'HAT'

export const CHARACTER = {
  UMDAAR: 'CHARACTER.UMDAAR',
  NOBILIS: {
    POWER: 'CHARACTER.NOBILIS.POWER',
    IMPERATOR: 'CHARACTER.NOBILIS.IMPERATOR',
    MIMIC: 'CHARACTER.NOBILIS.MIMIC',
    STRATEGIST: 'CHARACTER.NOBILIS.STRATEGIST',
    WARMAIN: 'CHARACTER.NOBILIS.WARMAIN',
    ZU: 'CHARACTER.NOBILIS.ZU'
  }
}

export const NAME = {
  BARBARIAN: 'NAME.BARBARIAN'
}

export const SPELL = {
  FOTF: 'SPELL.FOTF'
}
